In [1]:
print("hello World")

hello World

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv(r"C:\Users\akand\Documents\data journey\Amdari Resources\Python Amdari\nova_pay_combined.csv")

In [7]:
print(df.head())

                         transaction_id                           customer_id  \
0  fee8542d-8ee6-4b0d-9671-c294dd08ed26  402cccc9-28de-45b3-9af7-cc5302aa1f93
1  bfdb9fc1-27fe-4a85-b043-4d813d679259  67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad
2  fc855034-3ea5-4993-9afa-b511d93fe5e8  6d0d9b27-fa26-45f8-93b1-2df29d182d9c
3  2cf8c08e-42ec-444d-a755-34b9a2a0a4ca  7bd5200c-5d19-44f0-9afe-8b339a05366b
4  d907a74d-b426-438d-97eb-dbe911aca91c  70a93d26-8e3a-4179-900c-a4a7a74d08e5

                          timestamp home_country source_currency  \
0  2022-10-03 18:40:59.468549+00:00           US             USD
1  2022-10-03 20:39:38.468549+00:00           CA             CAD
2  2022-10-03 23:02:43.468549+00:00           US             USD
3  2022-10-04 01:08:53.468549+00:00           US             USD
4  2022-10-04 09:35:03.468549+00:00           US             USD

  dest_currency channel amount_src  amount_usd   fee  ...  ip_risk_score  \
0           CAD     ATM     278.19      278.19  4.25  ...          0.123
1           MXN     web     208.51      154.29  4.24  ...          0.569
2           CNY  mobile     160.33      160.33  2.70  ...          0.437
3           EUR  mobile      59.41       59.41  2.22  ...          0.594
4           INR  mobile     200.96      200.96  3.61  ...          0.121

   kyc_tier  account_age_days device_trust_score chargeback_history_count  \
0  standard               263              0.522                        0
1  standard               947              0.475                        0
2  enhanced               367              0.939                        0
3  standard               147              0.551                        0
4  enhanced               257              0.894                        0

   risk_score_internal  txn_velocity_1h txn_velocity_24h  corridor_risk  \
0                0.223                0                0            0.0
1                0.268                0                1            0.0
2                0.176                0                0            0.0
3                0.391                0                0            0.0
4                0.257                0                0            0.0

   is_fraud
0         0
1         0
2         0
3         0
4         0

[5 rows x 26 columns]

In [10]:
df.shape

(11400, 26)

In [11]:
df.sample(5)

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
6983,ae93527d-f8b5-4a64-97a7-2e30ff87acbf,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2024-11-06 06:04:44.468549+00:00,US,USD,CNY,web,177.25,177.25,3.57,...,0.136,enhanced,257,0.894,0,0.257,0,0,0.0,0
4036,5263bbdf-1a0a-48a3-8309-3f6b5b57d4a6,402cccc9-28de-45b3-9af7-cc5302aa1f93,2023-12-22 05:41:50.468549+00:00,US,USD,USD,mobile,61.49,61.49,1.08,...,0.235,standard,263,0.522,0,0.223,0,0,0.0,0
4543,eaedef09-4e7d-402c-8473-6c032b595358,af8ca4c4-8703-4c55-b66c-2b76cd70040d,2024-02-12 05:31:53.468549+00:00,US,USD,PHP,web,133.25,133.25,2.64,...,0.084,standard,1018,0.934,0,0.087,0,0,0.1,0
3053,1db2de79-ca53-4134-bba8-a79d7183e887,d71c91b4-fee8-4104-9856-a5c6109a62e3,2023-09-09 11:15:53.468549+00:00,US,USD,INR,web,40.49,40.49,1.34,...,0.206,standard,298,0.336,0,0.166,0,0,0.0,0
7357,b29b0ffe-16e6-4254-97a2-c3696e3c0ded,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2024-12-17 23:23:32.468549+00:00,US,USD,CAD,web,86.65,86.65,1.66,...,0.305,enhanced,257,0.894,0,0.257,0,0,0.0,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11400 entries, 0 to 11399
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             11400 non-null  str
 1   customer_id                11400 non-null  str
 2   timestamp                  11371 non-null  str
 3   home_country               11400 non-null  str
 4   source_currency            11400 non-null  str
 5   dest_currency              11400 non-null  str
 6   channel                    11400 non-null  str
 7   amount_src                 11400 non-null  str
 8   amount_usd                 11095 non-null  float64
 9   fee                        11105 non-null  float64
 10  exchange_rate_src_to_dest  11400 non-null  float64
 11  device_id                  11400 non-null  str
 12  new_device                 11400 non-null  bool
 13  ip_address                 11095 non-null  str
 14  ip_country                 11099 non-null  str
 15  location_mismatch          11400 non-null  bool
 16  ip_risk_score              11400 non-null  float64
 17  kyc_tier                   11100 non-null  str
 18  account_age_days           11400 non-null  int64
 19  device_trust_score         11105 non-null  float64
 20  chargeback_history_count   11400 non-null  int64
 21  risk_score_internal        11400 non-null  float64
 22  txn_velocity_1h            11400 non-null  int64
 23  txn_velocity_24h           11400 non-null  int64
 24  corridor_risk              11400 non-null  float64
 25  is_fraud                   11400 non-null  int64
dtypes: bool(2), float64(7), int64(5), str(12)
memory usage: 2.1 MB

In [14]:
df.head(2)

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,ATM,278.19,278.19,4.25,...,0.123,standard,263,0.522,0,0.223,0,0,0.0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,...,0.569,standard,947,0.475,0,0.268,0,1,0.0,0

In [18]:
# ================================
#     QUICK SUMMARY REPORT
# ================================
print("===== QUICK SUMMARY REPORT =====")
print("Shape:", df.shape)
print("\nData types:\n", df.dtypes)
print("\nNumerical summary:\n", df.describe())
print("\nNumerical summary:\n", df.describe().round(2))
print("\nCategorical summary:\n", df.describe(include='object'));

===== QUICK SUMMARY REPORT =====
Shape: (11400, 26)

Data types:
 transaction_id                   str
customer_id                      str
timestamp                        str
home_country                     str
source_currency                  str
dest_currency                    str
channel                          str
amount_src                       str
amount_usd                   float64
fee                          float64
exchange_rate_src_to_dest    float64
device_id                        str
new_device                      bool
ip_address                       str
ip_country                       str
location_mismatch               bool
ip_risk_score                float64
kyc_tier                         str
account_age_days               int64
device_trust_score           float64
chargeback_history_count       int64
risk_score_internal          float64
txn_velocity_1h                int64
txn_velocity_24h               int64
corridor_risk                float64
is_fraud                       int64
dtype: object

Numerical summary:
          amount_usd           fee  exchange_rate_src_to_dest  ip_risk_score  \
count  11095.000000  11105.000000               11400.000000   11400.000000
mean     452.022083    100.309441                 167.540397       0.396726
std     1403.973062    958.128504                 382.023827       0.270507
min        7.230000     -1.000000                   0.592000       0.004000
25%       92.465000      2.380000                   1.000000       0.209000
50%      163.480000      3.500000                   7.142857       0.325000
75%      302.190000      5.550000                  73.529412       0.487000
max    12498.570000   9999.990000                1388.888889       1.200000

       account_age_days  device_trust_score  chargeback_history_count  \
count      11400.000000        11105.000000              11400.000000
mean         393.793158            0.653681                  0.048509
std          342.348393            0.273012                  0.256194
min            1.000000           -0.100000                  0.000000
25%          147.000000            0.515000                  0.000000
50%          298.000000            0.658000                  0.000000
75%          661.000000            0.894000                  0.000000
max         1095.000000            0.999000                  2.000000

       risk_score_internal  txn_velocity_1h  txn_velocity_24h  corridor_risk  \
count         11400.000000     11400.000000      11400.000000   11400.000000
mean              0.267134         0.458333          0.723509       0.045501
std               0.142983         1.524494          1.958390       0.084942
min               0.000000        -1.000000          0.000000       0.000000
25%               0.169000         0.000000          0.000000       0.000000
50%               0.223000         0.000000          0.000000       0.000000
75%               0.391000         0.000000          0.000000       0.050000
max               0.900000         8.000000         11.000000       0.250000

           is_fraud
count  11400.000000
mean       0.087456
std        0.282515
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

Numerical summary:
        amount_usd       fee  exchange_rate_src_to_dest  ip_risk_score  \
count    11095.00  11105.00                   11400.00       11400.00
mean       452.02    100.31                     167.54           0.40
std       1403.97    958.13                     382.02           0.27
min          7.23     -1.00                       0.59           0.00
25%         92.46      2.38                       1.00           0.21
50%        163.48      3.50                       7.14           0.32
75%        302.19      5.55                      73.53           0.49
max      12498.57   9999.99                    1388.89           1.20

       account_age_days  device_trust_score  chargeback_history_count  \
count          11400.00            11105.00                  11400.00
mean             393.79                0.65                      0.05
std              342.35                0.27                      0.26
min                1.00               -0.10                      0.00
25%              147.00                0.52                      0.00
50%              298.00                0.66                      0.00
75%              661.00                0.89                      0.00
max             1095.00                1.00                      2.00

       risk_score_internal  txn_velocity_1h  txn_velocity_24h  corridor_risk  \
count             11400.00         11400.00          11400.00       11400.00
mean                  0.27             0.46              0.72           0.05
std                   0.14             1.52              1.96           0.08
min                   0.00            -1.00              0.00           0.00
25%                   0.17             0.00              0.00           0.00
50%                   0.22             0.00              0.00           0.00
75%                   0.39             0.00              0.00           0.05
max                   0.90             8.00             11.00           0.25

       is_fraud
count  11400.00
mean       0.09
std        0.28
min        0.00
25%        0.00
50%        0.00
75%        0.00
max        1.00

C:\Users\akand\AppData\Local\Temp\ipykernel_35732\1032011966.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("\nCategorical summary:\n", df.describe(include='object'));

Categorical summary:
                               transaction_id  \
count                                  11400
unique                                 11200
top     4662cb2d-21b2-4390-ba38-5a1eddebdc7c
freq                                       2

                                 customer_id             timestamp  \
count                                  11400                 11371
unique                                  1315                 11141
top     402cccc9-28de-45b3-9af7-cc5302aa1f93  0000-00-00T00:00:00Z
freq                                    1510                    21

       home_country source_currency dest_currency channel amount_src  \
count         11400           11400         11400   11400      11400
unique            7               3             9      12       9850
top              US             USD           NGN  mobile        100
freq           7940            8031          1474    6366         15

                                   device_id      ip_address ip_country  \
count                                  11400           11095      11099
unique                                  2113           10900          9
top     e70db499-19e1-4927-b04f-3ebfcf62e33c  194.179.17.152         US
freq                                      87               2       6848

        kyc_tier
count      11100
unique        14
top     standard
freq        7931